# Generated by Django 5.0.4 on 2024-04-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Destination',
        ),
    ]
