# Generated by Django 5.0.4 on 2024-04-22 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_category_destination_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.category'),
        ),
    ]
