# Generated by Django 5.0.4 on 2024-04-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_destination_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
