# Generated by Django 5.0.4 on 2024-04-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_alter_category_table_alter_destination_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['name', 'title', 'description', 'category']},
        ),
    ]
